name: Feature build

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: SSH Setup
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PRIVATE_DEPENDENCY }}

      - name: Clone publicgoods-website-test
        run: git clone git@github.com:DPGAlliance/DPGAlliance.github.io.git ../publicgoods-website-test

      - name: Run npm i at root for needed react-scripts package below
        run: npm install

      - name: Consolidating DPG's and nominees from new API for registry page table
        run: cd packages/automation && node consolidate_data.js

      - name: Generating registry, eligibility and map pages
        run: cd packages/automation && node index.js

      - name: Softlink required dependencies
        run: |
          ln -s ../../../../publicgoods-website-test/wp-includes/ packages/eligibility/public/wp-includes;
          ln -s ../../../../publicgoods-website-test/wp-content/ packages/eligibility/public/wp-content;
          ln -s ../../../../publicgoods-website-test/wp-includes/ packages/registry/public/wp-includes;
          ln -s ../../../../publicgoods-website-test/wp-content/ packages/registry/public/wp-content;
          ln -s ../../../../publicgoods-website-test/wp-includes/ packages/map/public/wp-includes;
          ln -s ../../../../publicgoods-website-test/wp-content/ packages/map/public/wp-content;
          ln -s ../../../../publicgoods-website-test/wp-includes/ packages/roadmap/public/wp-includes;
          ln -s ../../../../publicgoods-website-test/wp-content/ packages/roadmap/public/wp-content;

      - name: Build packages/eligibility
        run: cd packages/eligibility && npm install && npm run build

      - name: Build packages/registry
        run: cd packages/registry && npm install && npm run build

      - name: Build packages/roadmap
        run: cd packages/roadmap && npm install && npm run build

      - name: run movefiles.bash
        run: bash scripts/moveFiles.bash
